libsigcplusplus/libsigcplusplus

configure.ac
current url in AC_INIT is broken, I imagine the github webpage serves as a good stand in replacement?
=> fix broken url

configure.ac
Without the `foreign` option, automake requires a README file, which no
longer exists.
Makefile.am: error: required file './README' not found
Fixes: 8a0cb176 ("README: Rename to README.md and reformat as markdown")
=> configure.ac: Set `foreign` option to fix build

sigc++/weak_raw_ptr.h
Copy constructor and `operator=` could fail if `src` was empty.
```
sigc::connection con1;
sigc::connection con2(con1); // failed
```
```
sigc::connection con3;
sigc::connection con4;
con3 = con4; // failed
```
=> Empty connections can be safely copied now

.github/workflows/autotools-clang-5.yml, .github/workflows/autotools-clang-6.yml, .github/workflows/autotools-clang-7.yml, .github/workflows/autotools-clang-8.yml, .github/workflows/autotools-gcc-7.yml, .github/workflows/autotools-gcc-8.yml, .github/workflows/autotools-gcc-9.yml
This enables more warnings and makes the build fail if they happen.
=> Github Actions: Use --enable-warnings=fatal

CMakeLists.txt, sigc++/tuple-utils/tuple_end.h, sigc++/tuple-utils/tuple_for_each.h, sigc++/tuple-utils/tuple_transform_each.h, sigc++/visit_each.h, tests/CMakeLists.txt
This pull request adds warning flags '/W4 /WX' to the MSVC build created with CMake from the CMakeLists.txt files in the build. This also includes code to remove the '/W3' warning level flag that CMake has in its MSVC compiler flag defaults.
There is also code to set the default GCC/Clang compiler flags. These defaults have been taken from the configure.ac in the build.
=> MSVC build: Add default warning flags to CMake build

.github/workflows/autotools-clang-8.yml
The uses: line was actually a separate step that didn't influence the
following step. Ubuntu 18.04 (what GitHub actions uses for
"ubuntu-latest") actually has clang-8 anyway.
=> GitHub Actions CI: autotools-clang-8: Don't try to use Ubuntu 19.10

.github/workflows/autotools-clang-5.yml, .github/workflows/autotools-clang-6.yml, .github/workflows/autotools-clang-7.yml, .github/workflows/autotools-clang-8.yml, .github/workflows/autotools-clang-9.yml, .github/workflows/autotools-gcc-7.yml, .github/workflows/autotools-gcc-8.yml, .github/workflows/autotools-gcc-9.yml
As in the build step. Otherwise, the distcheck's configure run will
just pick up the default compiler again.
=> GitHub Actions CI: Specify CXX before make distcheck

tests/test_limit_reference.cc
Explicitly implement Bases's move constructor because the defaulted one
would call non-trivial assignment operators in the virtual bases.
And implement the default constructor too, because it is not
generated automatically if we implement the move constructor.
This avoids this compiler warning, at least with g++ 9.2:
test_limit_reference.cc:12:7: error: defaulted move assignment for ‘{anonymous}::Base’ calls a non-trivial move assignment operator for virtual base ‘sigc::trackable’ [-Werror=virtual-move-assign]
12 | class Base : virtual public sigc::trackable
|       ^~~~
test_limit_reference.cc:22:7: error: defaulted move assignment for ‘{anonymous}::Derived’ calls a non-trivial move assignment operator for virtual base ‘{anonymous}::Base’ [-Werror=virtual-move-assign]
22 | class Derived …
=> test_limit_reference: Avoid virtual-move-assign warning

.github/workflows/autotools-clang-5.yml, .github/workflows/autotools-clang-6.yml, .github/workflows/autotools-clang-7.yml, .github/workflows/autotools-clang-8.yml, .github/workflows/autotools-clang-9.yml, .github/workflows/autotools-gcc-7.yml, .github/workflows/autotools-gcc-8.yml, .github/workflows/autotools-gcc-9.yml
./autogen.sh already runs configure, passing the arguments.
This is why the builds didn't fail when there were compiler errors.
=> GitHub Actions CI: Remove extra configure calls

tests/test_compose.cc
This was apparently related to some long-since removed libsigc++ support
for a non-standard a gcc typeof() extension.
https://gcc.gnu.org/onlinedocs/gcc/Typeof.html
=> tests: Remove unused SIGC_CXX_TYPEOF alternative code

.gitignore, MSVC_NMake/meson.build, Makefile.am, docs/docs/manual/meson.build, docs/docs/reference/meson.build, examples/meson.build, meson.build, meson_options.txt, sigc++/meson.build, sigc++config.h.meson, tests/meson.build, tools/dist-cmd.py, tools/tutorial-custom-cmd.py, untracked/README
This PR shows how libsigc++-3.0 (master branch) can be built with Meson instead
of Autotools. libsigc++-3.0 does not contain built source code, which simplifies
the meson.build files, compared to for instance libsigc++-2.0 and pangomm.
When building libsigc++-3.0 in maintainer-mode, the mm-common-get command must be
available, but M4 is not used.
I have copied meson.build files from pangomm and modified them.
docs/docs/manual/libsigc_manual.xml is converted to html files and a pdf file
in a way similar to what's done in gtkmm-documentation.
@fanc999 and other persons working with MSVC:
Can this be used for MSVC builds? Are modifications necessary?
Can MSVC build directly from git, now that M4 is not used?
M4 is used when building libsigc++-2.0 (libsigc++-2-10 branch) from git,
but it's …
=> Add support for building libsigc++-3.0 with Meson

meson.build, sigc++/meson.build
Hi,
These are the simple additions that are required for the Meson build system for libsigc++-2.x so that it may be used for Visual Studio builds, too.
With blessings, thank you!
=> Fix Visual Studio builds via Meson (libsigc++-2.x)

.gitignore, MSVC_NMake/meson.build, Makefile.am, docs/manual/meson.build, docs/reference/meson.build, examples/meson.build, meson.build, meson_options.txt, sigc++/meson.build, sigc++config.h.meson, tests/meson.build, tools/dist-cmd.py, tools/gcc_template_specialization_operator_overload.cc, tools/handle-built-files.py, tools/have_sun_reverse_iterator.cc, tools/msvc_template_specialization_operator_overload.cc, tools/pragma_push_pop_macro.cc, tools/tutorial-custom-cmd.py, untracked/README
This PR shows how libsigc++-2.0 (libsigc++-2-10 branch) can be built with Meson instead
of Autotools. libsigc++-2.0 contains built source code, which complicates
the meson.build files, compared to libsigc++-3.0.
When building libsigc++-2.0 in maintainer-mode, the mm-common-get command and M4 are used.
I have copied meson.build files from pangomm and modified them.
docs/manual/libsigc_manual.xml is converted to html files and a pdf file
in a way similar to what's done in gtkmm-documentation.
@fanc999 and other persons working with MSVC:
Can this be used for MSVC builds? Are modifications necessary?
I suppose MSVC can't build directly from git, since M4 is used.
M4 is used when building libsigc++-2.0 (libsigc++-2-10 branch) from git,
but it's not used when building libsigc++-3.0 (master …
=> Add support for building libsigc++-2.0 with Meson

MSVC_NMake/build-rules-msvc.mak, MSVC_NMake/config-msvc.mak, MSVC_NMake/create-lists-msvc.mak, MSVC_NMake/detectenv-msvc.mak, MSVC_NMake/generate-msvc.mak, MSVC_NMake/install.mak, MSVC_NMake/meson.build, Makefile.am, meson.build, sigc++/meson.build, tools/handle-built-files.py
Hi,
I went a bit further to see whether we can build libsigc++ master in maintainer mode even on Visual Studio builds, and it turns out that it is indeed possible, but it does take some extra steps which involved installing <code>mm-common</code>, <code>doxygen</code>, and <code>GraphViz</code> (<code>GraphViz</code> involves installing a pretty recent mingw-w64).
It seems though, with the above items installed, we still need one small change to <code>meson.build</code> so that things will work, up to and including 'meson dist'.
From the commit message:
<i>Since we are assured that we are using Python 3.x on when we run Meson, we do not really need to look for the 'python3' executable, but we could just use whatever Python interpreter that is used to run Meson.</i>
<i>This will fix …
=> Meson: More fixes for Windows builds

MSVC_NMake/build-rules-msvc.mak, MSVC_NMake/config-msvc.mak, MSVC_NMake/create-lists-msvc.mak, MSVC_NMake/generate-msvc.mak, MSVC_NMake/install.mak, MSVC_NMake/meson.build, meson.build, sigc++/meson.build, tools/handle-built-files.py
Hi,
I went a bit further to refine things for the Meson builds on Visual Studio, namely:
*  Allow maintainer-mode/direct builds from GIT checkout on Visual Studio, too.  This is because one can install <code>m4</code> with mingw-w64 (and possibly Cygwin), which is sufficient for our needs here.
*  And all the changes in PR 51.
With blessings, thank you!
=> More fixes for Meson builds with Visual Studio (libsigc++-2-10)

.github/workflows/autotools-clang-10.yml
Like the clang-10 CI, this uses a newer Ubuntu version (20.04) by
specifying a different docker image.  Because of that, we no longer need
to use sudo with apt.
=> GitHub Actions CI: Add a clang++ 10 build

meson.build, sigc++/meson.build
This is necessary to ensure backwards compatibility with the libtool versioning scheme on macOS.
This PR is against the 2.10 branch. If this one is accepted, I will gladly open a similar one against master as well.
=> Meson build: fix versioning on macOS

.github/workflows/autotools-clang-8.yml, .github/workflows/autotools-clang-9.yml, .github/workflows/meson-clang-10.yml, .github/workflows/meson-gcc-9.yml
GitHub Actions now supports ubuntu-20.04 directly, not only via a
separate container:
https://github.com/actions/virtual-environments
And use ubuntu-18.04 instead of ubuntu-latest, because that's what it
currently is, but ubuntu-latest will change to mean ubuntu-20.04 soon:
https://github.com/actions/virtual-environments/issues/1816
=> GitHub actions: Use ubuntu-20.04 directly

.github/workflows/clang-format-check.yml, Makefile.am, sigc++/sigc++.h, sigc++config.h.in, sigc++config.h.meson, tests/test_bind.cc, tests/test_bind_refptr.cc, tests/test_cpp11_lambda.cc, tests/test_track_obj.cc
This requires clang-format from clang 10, because it uses the new --dry-run and --Werror options. So it uses Ubuntu 20.04.
=> CI: GitHub actions: check format

docs/docs/reference/meson.build, meson.build
This PR fixes 2/3 of issue #71.
- Fallback for find_program('mm-common-get', required: false) does not work. If the program is not required Meson prefer not using the fallback subproject. Changing it to find_program('mm-common-get', required: maintainer_mode) would make more sense since you error() just below anyway.
- When disabling documentation, 'doxytagfile': tag_file.full_path() fails because tag_file is not defined.
I'm not so sure about the last 1/3
- Building doc requires many extra deps (perl, etc), would be nice to make that optinal by default using a feature option that defaults to auto.
Is documentation a feature? Some C packages (glib, gtk, etc.) control the documentation
with a boolean option with default value `false`. There once was a glibmm issue
where one of the …
=> Fix build as subproject without building documentation

sigc++/functors/slot.h, sigc++/signal.h, sigc++/type_traits.h, tests/memleakcheck.sh, tests/meson.build, tests/test_rvalue_ref.cc
In code based on Glibmm it's quite common to convert a Glib C structure
to a Glib::Object's descendant before passing it as a parameter to a
slot. If the slot is not supposed to modify the object, then everything
is fine, we can declare the parameter as a const reference and the
temporary object will be accurately dealt with by the compiler. However,
if the Glib based object is getting modified, the only way to pass it to
the slot is to declare it a Glib::RefPtr shared pointer. This creates a
lot of unnecessary churn of memory allocations for a simple deal of
calling a signal. However, C++ has a specific mean for this particular
semantic of passing a temporary object: rvalue reference.
For example, somewhere inside Gtkmm might be a declaration:
```
_WRAP_SIGNAL(void sun_rose(const …
```
=> Allow slots with rvalue reference parameters

sigc++/functors/mem_fun.h, sigc++/functors/ptr_fun.h, tests/test_rvalue_ref.cc
This is a missed addition to the commit that allowed rvalue references
in slot parameters.
=> Add missing perfect forwarding in bound_mem_functor::operator()

meson.build, meson_options.txt
Allow the user to disable build of test programs
Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
=> add build_tests option

sigc++config.h.cmake, sigc++config.h.in, sigc++config.h.meson
Hi,
This attempts to clean up and update these `sigc++config.h.*` files a bit in regards to Visual Studio:
* Drop the workaround for using `noexcept`, since we require Visual Studio 2017 or later for libsigc++-3.x.
* Sadly, the `warning C4251` in the comments still applies today, and attempting to try to see whether we can export `std::list` can risk breaking ABI, so update the comment there.
---
Do we still have any libsigc++-2.x versions beyond 2.12?  If so, I think we could just drop VS2013 support, since the latest C++11 releases of items that use libsigc++-2.x would actually require VS2015 (or even VS2017 for libxml++-3.x) or later.
---
With blessings, thank you!
=> sigc++config.h.*: Update and clean up a bit for Visual Studio

sigc++/functors/slot.h, sigc++/signal.h
This can lead to clearer errors by explaining the user's error, not just saying they used an incomplete type (why is it incomplete?). I don't use only static_assert(false) because that's ill-formed before C++23, AFAIK, & even if it's OK in some cases I don't grok which... so hope this works
My hope is that by using the weird `sizeof` comparison, it bypasses the issue with `static_assert(false)`, based on topics like this:
* https://stackoverflow.com/questions/40783712/disable-template-but-allow-specializations
Tests build and run fine on `g++ (Debian 13.2.0-6) 13.2.0` but I would appreciate more coverage on other compilers.
If we do this, we should do equivalent for `Glib::SignalProxy` in `glibmm`.
Fixes https://github.com/libsigcplusplus/libsigcplusplus/issues/86
=> slot|signal: static_assert not using R,T... syntax

meson.build
This fixes DLL linkage with clang-cl or intel-cl.
=> Meson: Detect cl-like compilers

sigc++/filelist.am, sigc++/meson.build, sigc++/sigc++.h, sigc++/signal_base.h, sigc++/signal_connect.h, tests/CMakeLists.txt, tests/Makefile.am, tests/meson.build, tests/test_signal_connect.cc
After discussion in #104, there are finally more than 3 versions of `signc::signal_connect(...)`:
* 1 for lambdas and std::function;
* 1 using `sigc::ptr_fun(...)` for function pointers;
* 1 using `sigc::bind(sigc::ptr_fun<...>(...)` for function pointers with partially or totally bound arguments;
* 4 `sigc::mem_fun(...)` for methods (one for each the non-cv one and the 3 cv ones);
* 4 `sigc::bind(sigc::mem_fun<...>(...)` for  methods (for the same reason).
I think the test program can be used as a good showcase (instead of writing an example program) and I don't have any changes for the documentation yet.
**But** I face 2 problems (hence the WIP prefix):
1. Clang does not accept the `sigc::mem_fun(...)` with overloaded methods while GCC does.
2. Clang and GCC do not accept …
=> Add signal connect helpers

sigc++/signal_connect.h, tests/test_signal_connect.cc
Hello,
Here is a (far) better way to fix the ambiguity with MSVC I tried to solved in #107.
Sorry for the inconvenience.
=> Simplify ambiguity removal when compiling with MSVC

tools/tutorial-custom-cmd.py
If a font (usually from texlive) is missing, dblatex goes on an infinite loop and prints no error message (not even in logs).
Issue happened because a dependency update on my side might be missing from dblatex package. In any case, should fail and print something useful, not go on forever. Failing on error really should be a dblatex built-in default, but upstream seems dead, therefore adding safety here.
Should be applied on both 2.12.x and 3.x branches. Tested with release libsigc 2.12.1 and 3.6.0.
=> build-pdf: Prevent infinite loop in dblatex
